spring.application.name=Apis
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/aeros/OneDrive/Desktop
spring.datasource.username=sourabh
spring.datasource.password=sourabh123
spring.jpa.hibernate.ddl-auto=update